server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ruiji?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: oaoj3210

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  thymeleaf:
    cache: false

  aop:
    proxy-target-class: true
  cache:
    type:
      redis

mybatis:
  type-aliases-package: com.jc.job.domain, com.jc.system.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  type-handlers-package: com.jc.common.util.enums

mapper:
  mappers: com.jc.common.config.MyMapper
  not-empty: false
  identity: false


mybatis:
  # type-aliases扫描路径
  type-aliases-package: com.xsz.system.domain,com.xsz.job.domain
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  # 多个模块的的多个包配置可以使用逗号分开
  type-handlers-package: com.xsz.common.util.enums

#文件上传路径
file.upload.path: F://images//
file.upload.path.relative: /images/
imagesPath: file:/F:/images/

mapper:
  mappers: com.xsz.common.config.MyMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# XSZ 配置
febs:
  # 是否在控制台打印 sql语句
  showsql: true
  # 时间类型参数在前端页面的展示格式，默认格式为 yyyy-MM-dd HH:mm:ss
  timeFormat: yyyy-MM-dd HH:mm:ss
  # 是否开启 AOP 日志，默认开启
  openAopLog: true
  shiro:
    # shiro redis缓存时长，默认1800秒
    expireIn: 1800
    # session 超时时间，默认1800000毫秒
    sessionTimeout: 1800000
    # rememberMe cookie有效时长，默认86400秒，即一天
    cookieTimeout: 86400
    # 免认证的路径配置，如静态资源，druid监控页面，注册页面，验证码请求等
    anonUrl: /css/**,/js/**,/fonts/**,/img/**,/druid/**,/user/regist,/gifCode,/,/actuator/**,/test/**
    # 登录 url
    loginUrl: /login
    # 登录成功后跳转的 url
    successUrl: /index
    # 登出 url
    logoutUrl: /logout
    # 未授权跳转 url
    unauthorizedUrl: /403
  # 验证码
  validateCode:
    # 宽度，默认 146px
    width: 146
    # 高度，默认 33px
    height: 33
    # 验证码字符个数，默认4个字符
    length: 4

# 自定义swagger开关
swagger:
  enabled: true